// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDathHJatwn5zN0yIej846Ewkz4r4adeZg',
    appId: '1:52400763251:web:34b2a8132be0b28b1a9506',
    messagingSenderId: '52400763251',
    projectId: 'testdeliveryapp-9f191',
    authDomain: 'testdeliveryapp-9f191.firebaseapp.com',
    storageBucket: 'testdeliveryapp-9f191.firebasestorage.app',
    measurementId: 'G-N9QZF5MCQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFd3azDmr8quQgCeqi-svLiGJAEaGCdU',
    appId: '1:52400763251:android:71d8b947aa0f15981a9506',
    messagingSenderId: '52400763251',
    projectId: 'testdeliveryapp-9f191',
    storageBucket: 'testdeliveryapp-9f191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4PMLkFFeM6PK6tT0YyIkWyOW-62TRj4',
    appId: '1:52400763251:ios:72fa37432f8b25ff1a9506',
    messagingSenderId: '52400763251',
    projectId: 'testdeliveryapp-9f191',
    storageBucket: 'testdeliveryapp-9f191.firebasestorage.app',
    iosBundleId: 'com.example.testDeliveryApp',
  );
}
